title: La malmesure des choses 
description: "Sequence Analysis for Time Use Research"

email: giacomovagni@domain.com

url: http://giacomovagni.github.io/mismeasure-of-things # the base hostname & protocol for your site

port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: G. Ecce
  disqus_shortname: gecce
  twitter: giacomoecce

categories: [sequence, rstats, time, things]
